[tool.poetry]
name = "bikefit"
version = "0.1.0"
description = ""
authors = ["du3 <du3@qad.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
